version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (*go.uber.org/zap.Logger).Sync
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'
      - linters:
          - revive
        text: "empty-block: this block is empty, you can remove it"
      - linters:
          - errcheck
        source: ^\s*defer\s+
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
